services:
  server:
    secrets:
      - db-password
    environment:
      - CELERY_BROKER_URL='redis://redis:6379/0'
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=example
    depends_on:
      - run_db_migrations
      - redis
    build:
      context: .
    ports:
      - 8000:8000
  run_db_migrations:
    secrets:
      - db-password
    environment:
      - CELERY_BROKER_URL='redis://redis:6379/0'
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=example
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
    command: "python /app/manage.py migrate"
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    restart: always
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt